---
version: "3.7"
services:
  gago:
    tty: true
    stdin_open: true
    build:
      context: .
    ports:
      - "2222:22"
    environment:
      - PASS=${PASSWORD}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Europe/London
    volumes:
      - ./home:/home
      - ./leaderboard:/leaderboard
      - ./scripts:/scripts
      - ./config:/config
      - ./etc/passwd:/opt/etc/passwd
      - ./etc/shadow:/opt/etc/shadow
      - ./etc/group:/opt/etc/group
      - ./etc/gshadow:/opt/etc/gshadow
      - ./snapshots:/snapshots
    restart: always
