---
version: "3.3"
services:
  gago:
    build:
      context: .
    container_name: gago
    ports:
      - "47060:22"
    environment:
      - PASS=${PASSWORD}
      - TZ=Europe/London
    volumes:
      - ./home:/home
      - ./src:/src
      - ./scripts:/scripts
      - ./config:/config
      - ./etc/passwd:/opt/etc/passwd
      - ./etc/shadow:/opt/etc/shadow
      - ./etc/group:/opt/etc/group
      - ./etc/gshadow:/opt/etc/gshadow
      - ./snapshots:/snapshots
    restart: unless-stopped
  discord:
    build:
      context: .
    container_name: discord
    network_mode: host
    working_dir: /src
    entrypoint: python3 -m bot.discrd.discrd
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Europe/London
    volumes:
      - /etc/hosts:/etc/hosts
      - ./src:/src
      - ./home:/home
      - ./config:/config
    restart: unless-stopped
