---
version: "3.3"
services:
  gago:
    build:
      context: .
    ports:
      - "127.0.0.1:2222:22"
    environment:
      - PASS=${PASSWORD}
      - TZ=Europe/London
    volumes:
      - ./home:/home
      - ./leaderboard:/leaderboard
      - ./scripts:/scripts
      - ./config:/config
      - ./etc/passwd:/opt/etc/passwd
      - ./etc/shadow:/opt/etc/shadow
      - ./etc/group:/opt/etc/group
      - ./etc/gshadow:/opt/etc/gshadow
      - ./snapshots:/snapshots
    restart: unless-stopped
  discord:
    build:
      context: .
    working_dir: /leaderboard
    entrypoint: python3 -m bot.discrd
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Europe/London
    volumes:
      - ./leaderboard:/leaderboard
      - ./home:/home
      - ./config:/config
    restart: unless-stopped
